/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const ExternalOrganizationSortProperty = {
    CreatedAt: "created_at",
    MinusCreatedAt: "-created_at",
    Name: "name",
    MinusName: "-name",
};
/** @internal */
export const ExternalOrganizationSortProperty$inboundSchema = z.nativeEnum(ExternalOrganizationSortProperty);
/** @internal */
export const ExternalOrganizationSortProperty$outboundSchema = ExternalOrganizationSortProperty$inboundSchema;
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var ExternalOrganizationSortProperty$;
(function (ExternalOrganizationSortProperty$) {
    /** @deprecated use `ExternalOrganizationSortProperty$inboundSchema` instead. */
    ExternalOrganizationSortProperty$.inboundSchema = ExternalOrganizationSortProperty$inboundSchema;
    /** @deprecated use `ExternalOrganizationSortProperty$outboundSchema` instead. */
    ExternalOrganizationSortProperty$.outboundSchema = ExternalOrganizationSortProperty$outboundSchema;
})(ExternalOrganizationSortProperty$ || (ExternalOrganizationSortProperty$ = {}));
//# sourceMappingURL=externalorganizationsortproperty.js.map