"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.CustomerBenefitGrant$ = exports.CustomerBenefitGrant$outboundSchema = exports.CustomerBenefitGrant$inboundSchema = void 0;
exports.customerBenefitGrantToJSON = customerBenefitGrantToJSON;
exports.customerBenefitGrantFromJSON = customerBenefitGrantFromJSON;
const z = __importStar(require("zod"));
const schemas_js_1 = require("../../lib/schemas.js");
const customerbenefitgrantcustom_js_1 = require("./customerbenefitgrantcustom.js");
const customerbenefitgrantdiscord_js_1 = require("./customerbenefitgrantdiscord.js");
const customerbenefitgrantdownloadables_js_1 = require("./customerbenefitgrantdownloadables.js");
const customerbenefitgrantgithubrepository_js_1 = require("./customerbenefitgrantgithubrepository.js");
const customerbenefitgrantlicensekeys_js_1 = require("./customerbenefitgrantlicensekeys.js");
/** @internal */
exports.CustomerBenefitGrant$inboundSchema = z.union([
    customerbenefitgrantdiscord_js_1.CustomerBenefitGrantDiscord$inboundSchema,
    customerbenefitgrantgithubrepository_js_1.CustomerBenefitGrantGitHubRepository$inboundSchema,
    customerbenefitgrantdownloadables_js_1.CustomerBenefitGrantDownloadables$inboundSchema,
    customerbenefitgrantlicensekeys_js_1.CustomerBenefitGrantLicenseKeys$inboundSchema,
    customerbenefitgrantcustom_js_1.CustomerBenefitGrantCustom$inboundSchema,
]);
/** @internal */
exports.CustomerBenefitGrant$outboundSchema = z.union([
    customerbenefitgrantdiscord_js_1.CustomerBenefitGrantDiscord$outboundSchema,
    customerbenefitgrantgithubrepository_js_1.CustomerBenefitGrantGitHubRepository$outboundSchema,
    customerbenefitgrantdownloadables_js_1.CustomerBenefitGrantDownloadables$outboundSchema,
    customerbenefitgrantlicensekeys_js_1.CustomerBenefitGrantLicenseKeys$outboundSchema,
    customerbenefitgrantcustom_js_1.CustomerBenefitGrantCustom$outboundSchema,
]);
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
var CustomerBenefitGrant$;
(function (CustomerBenefitGrant$) {
    /** @deprecated use `CustomerBenefitGrant$inboundSchema` instead. */
    CustomerBenefitGrant$.inboundSchema = exports.CustomerBenefitGrant$inboundSchema;
    /** @deprecated use `CustomerBenefitGrant$outboundSchema` instead. */
    CustomerBenefitGrant$.outboundSchema = exports.CustomerBenefitGrant$outboundSchema;
})(CustomerBenefitGrant$ || (exports.CustomerBenefitGrant$ = CustomerBenefitGrant$ = {}));
function customerBenefitGrantToJSON(customerBenefitGrant) {
    return JSON.stringify(exports.CustomerBenefitGrant$outboundSchema.parse(customerBenefitGrant));
}
function customerBenefitGrantFromJSON(jsonString) {
    return (0, schemas_js_1.safeParse)(jsonString, (x) => exports.CustomerBenefitGrant$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'CustomerBenefitGrant' from JSON`);
}
//# sourceMappingURL=customerbenefitgrant.js.map