/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
/** @internal */
export const OrganizationSubscribePromoteSettings$inboundSchema = z.object({
    promote: z.boolean().default(true),
    show_count: z.boolean().default(true),
    count_free: z.boolean().default(true),
}).transform((v) => {
    return remap$(v, {
        "show_count": "showCount",
        "count_free": "countFree",
    });
});
/** @internal */
export const OrganizationSubscribePromoteSettings$outboundSchema = z.object({
    promote: z.boolean().default(true),
    showCount: z.boolean().default(true),
    countFree: z.boolean().default(true),
}).transform((v) => {
    return remap$(v, {
        showCount: "show_count",
        countFree: "count_free",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var OrganizationSubscribePromoteSettings$;
(function (OrganizationSubscribePromoteSettings$) {
    /** @deprecated use `OrganizationSubscribePromoteSettings$inboundSchema` instead. */
    OrganizationSubscribePromoteSettings$.inboundSchema = OrganizationSubscribePromoteSettings$inboundSchema;
    /** @deprecated use `OrganizationSubscribePromoteSettings$outboundSchema` instead. */
    OrganizationSubscribePromoteSettings$.outboundSchema = OrganizationSubscribePromoteSettings$outboundSchema;
})(OrganizationSubscribePromoteSettings$ || (OrganizationSubscribePromoteSettings$ = {}));
export function organizationSubscribePromoteSettingsToJSON(organizationSubscribePromoteSettings) {
    return JSON.stringify(OrganizationSubscribePromoteSettings$outboundSchema.parse(organizationSubscribePromoteSettings));
}
export function organizationSubscribePromoteSettingsFromJSON(jsonString) {
    return safeParse(jsonString, (x) => OrganizationSubscribePromoteSettings$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'OrganizationSubscribePromoteSettings' from JSON`);
}
//# sourceMappingURL=organizationsubscribepromotesettings.js.map