/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export class RefundAmountTooHigh extends Error {
    constructor(err) {
        const message = "message" in err && typeof err.message === "string"
            ? err.message
            : `API error occurred: ${JSON.stringify(err)}`;
        super(message);
        this.data$ = err;
        this.error = err.error;
        this.detail = err.detail;
        this.name = "RefundAmountTooHigh";
    }
}
/** @internal */
export const RefundAmountTooHigh$inboundSchema = z.object({
    error: z.literal("RefundAmountTooHigh"),
    detail: z.string(),
})
    .transform((v) => {
    return new RefundAmountTooHigh(v);
});
/** @internal */
export const RefundAmountTooHigh$outboundSchema = z.instanceof(RefundAmountTooHigh)
    .transform(v => v.data$)
    .pipe(z.object({
    error: z.literal("RefundAmountTooHigh").default("RefundAmountTooHigh"),
    detail: z.string(),
}));
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var RefundAmountTooHigh$;
(function (RefundAmountTooHigh$) {
    /** @deprecated use `RefundAmountTooHigh$inboundSchema` instead. */
    RefundAmountTooHigh$.inboundSchema = RefundAmountTooHigh$inboundSchema;
    /** @deprecated use `RefundAmountTooHigh$outboundSchema` instead. */
    RefundAmountTooHigh$.outboundSchema = RefundAmountTooHigh$outboundSchema;
})(RefundAmountTooHigh$ || (RefundAmountTooHigh$ = {}));
//# sourceMappingURL=refundamounttoohigh.js.map