"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.CustomerSortProperty$ = exports.CustomerSortProperty$outboundSchema = exports.CustomerSortProperty$inboundSchema = exports.CustomerSortProperty = void 0;
const z = __importStar(require("zod"));
exports.CustomerSortProperty = {
    CreatedAt: "created_at",
    MinusCreatedAt: "-created_at",
    Email: "email",
    MinusEmail: "-email",
    Name: "name",
    MinusName: "-name",
};
/** @internal */
exports.CustomerSortProperty$inboundSchema = z.nativeEnum(exports.CustomerSortProperty);
/** @internal */
exports.CustomerSortProperty$outboundSchema = exports.CustomerSortProperty$inboundSchema;
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
var CustomerSortProperty$;
(function (CustomerSortProperty$) {
    /** @deprecated use `CustomerSortProperty$inboundSchema` instead. */
    CustomerSortProperty$.inboundSchema = exports.CustomerSortProperty$inboundSchema;
    /** @deprecated use `CustomerSortProperty$outboundSchema` instead. */
    CustomerSortProperty$.outboundSchema = exports.CustomerSortProperty$outboundSchema;
})(CustomerSortProperty$ || (exports.CustomerSortProperty$ = CustomerSortProperty$ = {}));
//# sourceMappingURL=customersortproperty.js.map