/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export class ResourceNotFound extends Error {
    constructor(err) {
        const message = "message" in err && typeof err.message === "string"
            ? err.message
            : `API error occurred: ${JSON.stringify(err)}`;
        super(message);
        this.data$ = err;
        this.error = err.error;
        this.detail = err.detail;
        this.name = "ResourceNotFound";
    }
}
/** @internal */
export const ResourceNotFound$inboundSchema = z.object({
    error: z.literal("ResourceNotFound"),
    detail: z.string(),
})
    .transform((v) => {
    return new ResourceNotFound(v);
});
/** @internal */
export const ResourceNotFound$outboundSchema = z.instanceof(ResourceNotFound)
    .transform(v => v.data$)
    .pipe(z.object({
    error: z.literal("ResourceNotFound").default("ResourceNotFound"),
    detail: z.string(),
}));
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var ResourceNotFound$;
(function (ResourceNotFound$) {
    /** @deprecated use `ResourceNotFound$inboundSchema` instead. */
    ResourceNotFound$.inboundSchema = ResourceNotFound$inboundSchema;
    /** @deprecated use `ResourceNotFound$outboundSchema` instead. */
    ResourceNotFound$.outboundSchema = ResourceNotFound$outboundSchema;
})(ResourceNotFound$ || (ResourceNotFound$ = {}));
//# sourceMappingURL=resourcenotfound.js.map