"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.CustomerOrganization$ = exports.CustomerOrganization$outboundSchema = exports.CustomerOrganization$inboundSchema = void 0;
exports.customerOrganizationToJSON = customerOrganizationToJSON;
exports.customerOrganizationFromJSON = customerOrganizationFromJSON;
const z = __importStar(require("zod"));
const schemas_js_1 = require("../../lib/schemas.js");
const customerproduct_js_1 = require("./customerproduct.js");
const organization_js_1 = require("./organization.js");
/** @internal */
exports.CustomerOrganization$inboundSchema = z.object({
    organization: organization_js_1.Organization$inboundSchema,
    products: z.array(customerproduct_js_1.CustomerProduct$inboundSchema),
});
/** @internal */
exports.CustomerOrganization$outboundSchema = z.object({
    organization: organization_js_1.Organization$outboundSchema,
    products: z.array(customerproduct_js_1.CustomerProduct$outboundSchema),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
var CustomerOrganization$;
(function (CustomerOrganization$) {
    /** @deprecated use `CustomerOrganization$inboundSchema` instead. */
    CustomerOrganization$.inboundSchema = exports.CustomerOrganization$inboundSchema;
    /** @deprecated use `CustomerOrganization$outboundSchema` instead. */
    CustomerOrganization$.outboundSchema = exports.CustomerOrganization$outboundSchema;
})(CustomerOrganization$ || (exports.CustomerOrganization$ = CustomerOrganization$ = {}));
function customerOrganizationToJSON(customerOrganization) {
    return JSON.stringify(exports.CustomerOrganization$outboundSchema.parse(customerOrganization));
}
function customerOrganizationFromJSON(jsonString) {
    return (0, schemas_js_1.safeParse)(jsonString, (x) => exports.CustomerOrganization$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'CustomerOrganization' from JSON`);
}
//# sourceMappingURL=customerorganization.js.map