/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { OAuth2Client$inboundSchema, OAuth2Client$outboundSchema, } from "./oauth2client.js";
import { Pagination$inboundSchema, Pagination$outboundSchema, } from "./pagination.js";
/** @internal */
export const ListResourceOAuth2Client$inboundSchema = z.object({
    items: z.array(OAuth2Client$inboundSchema),
    pagination: Pagination$inboundSchema,
});
/** @internal */
export const ListResourceOAuth2Client$outboundSchema = z.object({
    items: z.array(OAuth2Client$outboundSchema),
    pagination: Pagination$outboundSchema,
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var ListResourceOAuth2Client$;
(function (ListResourceOAuth2Client$) {
    /** @deprecated use `ListResourceOAuth2Client$inboundSchema` instead. */
    ListResourceOAuth2Client$.inboundSchema = ListResourceOAuth2Client$inboundSchema;
    /** @deprecated use `ListResourceOAuth2Client$outboundSchema` instead. */
    ListResourceOAuth2Client$.outboundSchema = ListResourceOAuth2Client$outboundSchema;
})(ListResourceOAuth2Client$ || (ListResourceOAuth2Client$ = {}));
export function listResourceOAuth2ClientToJSON(listResourceOAuth2Client) {
    return JSON.stringify(ListResourceOAuth2Client$outboundSchema.parse(listResourceOAuth2Client));
}
export function listResourceOAuth2ClientFromJSON(jsonString) {
    return safeParse(jsonString, (x) => ListResourceOAuth2Client$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ListResourceOAuth2Client' from JSON`);
}
//# sourceMappingURL=listresourceoauth2client.js.map