# Netlify configuration file

[build]
  command = "npm run build-no-errors"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  # Important: Ensure Vite processes these environment variables during build
  VITE_SUPABASE_URL = "${VITE_SUPABASE_URL}"
  VITE_SUPABASE_ANON_KEY = "${VITE_SUPABASE_ANON_KEY}"
  VITE_SUPABASE_PROJECT_ID = "${SUPABASE_PROJECT_ID}"
  VITE_SUPABASE_SERVICE_KEY = "${SUPABASE_SERVICE_KEY}"
  VITE_POLAR_ACCESS_TOKEN = "${VITE_POLAR_ACCESS_TOKEN}"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Set cache headers for assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
