"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.mcpScopes = void 0;
exports.mcpScopes = [
    "customers",
    "metrics",
    "orders",
    "products",
    "read",
    "subscriptions",
    "write",
];
//# sourceMappingURL=scopes.js.map