"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.CheckoutLinksCreateCheckoutLinkCreate$ = exports.CheckoutLinksCreateCheckoutLinkCreate$outboundSchema = exports.CheckoutLinksCreateCheckoutLinkCreate$inboundSchema = void 0;
exports.checkoutLinksCreateCheckoutLinkCreateToJSON = checkoutLinksCreateCheckoutLinkCreateToJSON;
exports.checkoutLinksCreateCheckoutLinkCreateFromJSON = checkoutLinksCreateCheckoutLinkCreateFromJSON;
const z = __importStar(require("zod"));
const schemas_js_1 = require("../../lib/schemas.js");
const checkoutlinkcreateproduct_js_1 = require("../components/checkoutlinkcreateproduct.js");
const checkoutlinkcreateproductprice_js_1 = require("../components/checkoutlinkcreateproductprice.js");
const checkoutlinkcreateproducts_js_1 = require("../components/checkoutlinkcreateproducts.js");
/** @internal */
exports.CheckoutLinksCreateCheckoutLinkCreate$inboundSchema = z.union([
    checkoutlinkcreateproductprice_js_1.CheckoutLinkCreateProductPrice$inboundSchema,
    checkoutlinkcreateproduct_js_1.CheckoutLinkCreateProduct$inboundSchema,
    checkoutlinkcreateproducts_js_1.CheckoutLinkCreateProducts$inboundSchema,
]);
/** @internal */
exports.CheckoutLinksCreateCheckoutLinkCreate$outboundSchema = z.union([
    checkoutlinkcreateproductprice_js_1.CheckoutLinkCreateProductPrice$outboundSchema,
    checkoutlinkcreateproduct_js_1.CheckoutLinkCreateProduct$outboundSchema,
    checkoutlinkcreateproducts_js_1.CheckoutLinkCreateProducts$outboundSchema,
]);
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
var CheckoutLinksCreateCheckoutLinkCreate$;
(function (CheckoutLinksCreateCheckoutLinkCreate$) {
    /** @deprecated use `CheckoutLinksCreateCheckoutLinkCreate$inboundSchema` instead. */
    CheckoutLinksCreateCheckoutLinkCreate$.inboundSchema = exports.CheckoutLinksCreateCheckoutLinkCreate$inboundSchema;
    /** @deprecated use `CheckoutLinksCreateCheckoutLinkCreate$outboundSchema` instead. */
    CheckoutLinksCreateCheckoutLinkCreate$.outboundSchema = exports.CheckoutLinksCreateCheckoutLinkCreate$outboundSchema;
})(CheckoutLinksCreateCheckoutLinkCreate$ || (exports.CheckoutLinksCreateCheckoutLinkCreate$ = CheckoutLinksCreateCheckoutLinkCreate$ = {}));
function checkoutLinksCreateCheckoutLinkCreateToJSON(checkoutLinksCreateCheckoutLinkCreate) {
    return JSON.stringify(exports.CheckoutLinksCreateCheckoutLinkCreate$outboundSchema.parse(checkoutLinksCreateCheckoutLinkCreate));
}
function checkoutLinksCreateCheckoutLinkCreateFromJSON(jsonString) {
    return (0, schemas_js_1.safeParse)(jsonString, (x) => exports.CheckoutLinksCreateCheckoutLinkCreate$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'CheckoutLinksCreateCheckoutLinkCreate' from JSON`);
}
//# sourceMappingURL=checkoutlinkscreate.js.map