"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.MetersGetRequest$ = exports.MetersGetRequest$outboundSchema = exports.MetersGetRequest$inboundSchema = void 0;
exports.metersGetRequestToJSON = metersGetRequestToJSON;
exports.metersGetRequestFromJSON = metersGetRequestFromJSON;
const z = __importStar(require("zod"));
const schemas_js_1 = require("../../lib/schemas.js");
/** @internal */
exports.MetersGetRequest$inboundSchema = z.object({
    id: z.string(),
});
/** @internal */
exports.MetersGetRequest$outboundSchema = z.object({
    id: z.string(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
var MetersGetRequest$;
(function (MetersGetRequest$) {
    /** @deprecated use `MetersGetRequest$inboundSchema` instead. */
    MetersGetRequest$.inboundSchema = exports.MetersGetRequest$inboundSchema;
    /** @deprecated use `MetersGetRequest$outboundSchema` instead. */
    MetersGetRequest$.outboundSchema = exports.MetersGetRequest$outboundSchema;
})(MetersGetRequest$ || (exports.MetersGetRequest$ = MetersGetRequest$ = {}));
function metersGetRequestToJSON(metersGetRequest) {
    return JSON.stringify(exports.MetersGetRequest$outboundSchema.parse(metersGetRequest));
}
function metersGetRequestFromJSON(jsonString) {
    return (0, schemas_js_1.safeParse)(jsonString, (x) => exports.MetersGetRequest$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'MetersGetRequest' from JSON`);
}
//# sourceMappingURL=metersget.js.map