/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
/** @internal */
export const OrderUser$inboundSchema = z.object({
    id: z.string(),
    email: z.string(),
    public_name: z.string(),
    avatar_url: z.nullable(z.string()).optional(),
    github_username: z.nullable(z.string()).optional(),
}).transform((v) => {
    return remap$(v, {
        "public_name": "publicName",
        "avatar_url": "avatarUrl",
        "github_username": "githubUsername",
    });
});
/** @internal */
export const OrderUser$outboundSchema = z.object({
    id: z.string(),
    email: z.string(),
    publicName: z.string(),
    avatarUrl: z.nullable(z.string()).optional(),
    githubUsername: z.nullable(z.string()).optional(),
}).transform((v) => {
    return remap$(v, {
        publicName: "public_name",
        avatarUrl: "avatar_url",
        githubUsername: "github_username",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var OrderUser$;
(function (OrderUser$) {
    /** @deprecated use `OrderUser$inboundSchema` instead. */
    OrderUser$.inboundSchema = OrderUser$inboundSchema;
    /** @deprecated use `OrderUser$outboundSchema` instead. */
    OrderUser$.outboundSchema = OrderUser$outboundSchema;
})(OrderUser$ || (OrderUser$ = {}));
export function orderUserToJSON(orderUser) {
    return JSON.stringify(OrderUser$outboundSchema.parse(orderUser));
}
export function orderUserFromJSON(jsonString) {
    return safeParse(jsonString, (x) => OrderUser$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'OrderUser' from JSON`);
}
//# sourceMappingURL=orderuser.js.map