"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.ListResourceUnionPaymentMethodCardPaymentMethodGeneric$ = exports.ListResourceUnionPaymentMethodCardPaymentMethodGeneric$outboundSchema = exports.ListResourceUnionPaymentMethodCardPaymentMethodGeneric$inboundSchema = exports.Items$ = exports.Items$outboundSchema = exports.Items$inboundSchema = void 0;
exports.itemsToJSON = itemsToJSON;
exports.itemsFromJSON = itemsFromJSON;
exports.listResourceUnionPaymentMethodCardPaymentMethodGenericToJSON = listResourceUnionPaymentMethodCardPaymentMethodGenericToJSON;
exports.listResourceUnionPaymentMethodCardPaymentMethodGenericFromJSON = listResourceUnionPaymentMethodCardPaymentMethodGenericFromJSON;
const z = __importStar(require("zod"));
const schemas_js_1 = require("../../lib/schemas.js");
const pagination_js_1 = require("./pagination.js");
const paymentmethodcard_js_1 = require("./paymentmethodcard.js");
const paymentmethodgeneric_js_1 = require("./paymentmethodgeneric.js");
/** @internal */
exports.Items$inboundSchema = z
    .union([paymentmethodgeneric_js_1.PaymentMethodGeneric$inboundSchema, paymentmethodcard_js_1.PaymentMethodCard$inboundSchema]);
/** @internal */
exports.Items$outboundSchema = z.union([
    paymentmethodgeneric_js_1.PaymentMethodGeneric$outboundSchema,
    paymentmethodcard_js_1.PaymentMethodCard$outboundSchema,
]);
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
var Items$;
(function (Items$) {
    /** @deprecated use `Items$inboundSchema` instead. */
    Items$.inboundSchema = exports.Items$inboundSchema;
    /** @deprecated use `Items$outboundSchema` instead. */
    Items$.outboundSchema = exports.Items$outboundSchema;
})(Items$ || (exports.Items$ = Items$ = {}));
function itemsToJSON(items) {
    return JSON.stringify(exports.Items$outboundSchema.parse(items));
}
function itemsFromJSON(jsonString) {
    return (0, schemas_js_1.safeParse)(jsonString, (x) => exports.Items$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'Items' from JSON`);
}
/** @internal */
exports.ListResourceUnionPaymentMethodCardPaymentMethodGeneric$inboundSchema = z.object({
    items: z.array(z.union([
        paymentmethodgeneric_js_1.PaymentMethodGeneric$inboundSchema,
        paymentmethodcard_js_1.PaymentMethodCard$inboundSchema,
    ])),
    pagination: pagination_js_1.Pagination$inboundSchema,
});
/** @internal */
exports.ListResourceUnionPaymentMethodCardPaymentMethodGeneric$outboundSchema = z.object({
    items: z.array(z.union([
        paymentmethodgeneric_js_1.PaymentMethodGeneric$outboundSchema,
        paymentmethodcard_js_1.PaymentMethodCard$outboundSchema,
    ])),
    pagination: pagination_js_1.Pagination$outboundSchema,
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
var ListResourceUnionPaymentMethodCardPaymentMethodGeneric$;
(function (ListResourceUnionPaymentMethodCardPaymentMethodGeneric$) {
    /** @deprecated use `ListResourceUnionPaymentMethodCardPaymentMethodGeneric$inboundSchema` instead. */
    ListResourceUnionPaymentMethodCardPaymentMethodGeneric$.inboundSchema = exports.ListResourceUnionPaymentMethodCardPaymentMethodGeneric$inboundSchema;
    /** @deprecated use `ListResourceUnionPaymentMethodCardPaymentMethodGeneric$outboundSchema` instead. */
    ListResourceUnionPaymentMethodCardPaymentMethodGeneric$.outboundSchema = exports.ListResourceUnionPaymentMethodCardPaymentMethodGeneric$outboundSchema;
})(ListResourceUnionPaymentMethodCardPaymentMethodGeneric$ || (exports.ListResourceUnionPaymentMethodCardPaymentMethodGeneric$ = ListResourceUnionPaymentMethodCardPaymentMethodGeneric$ = {}));
function listResourceUnionPaymentMethodCardPaymentMethodGenericToJSON(listResourceUnionPaymentMethodCardPaymentMethodGeneric) {
    return JSON.stringify(exports.ListResourceUnionPaymentMethodCardPaymentMethodGeneric$outboundSchema.parse(listResourceUnionPaymentMethodCardPaymentMethodGeneric));
}
function listResourceUnionPaymentMethodCardPaymentMethodGenericFromJSON(jsonString) {
    return (0, schemas_js_1.safeParse)(jsonString, (x) => exports.ListResourceUnionPaymentMethodCardPaymentMethodGeneric$inboundSchema
        .parse(JSON.parse(x)), `Failed to parse 'ListResourceUnionPaymentMethodCardPaymentMethodGeneric' from JSON`);
}
//# sourceMappingURL=listresourceunionpaymentmethodcardpaymentmethodgeneric.js.map