/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { BenefitDownloadablesCreateProperties$inboundSchema, BenefitDownloadablesCreateProperties$outboundSchema, } from "./benefitdownloadablescreateproperties.js";
/** @internal */
export const BenefitDownloadablesUpdate$inboundSchema = z.object({
    description: z.nullable(z.string()).optional(),
    type: z.literal("downloadables").optional(),
    properties: z.nullable(BenefitDownloadablesCreateProperties$inboundSchema)
        .optional(),
});
/** @internal */
export const BenefitDownloadablesUpdate$outboundSchema = z.object({
    description: z.nullable(z.string()).optional(),
    type: z.literal("downloadables").default("downloadables"),
    properties: z.nullable(BenefitDownloadablesCreateProperties$outboundSchema)
        .optional(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var BenefitDownloadablesUpdate$;
(function (BenefitDownloadablesUpdate$) {
    /** @deprecated use `BenefitDownloadablesUpdate$inboundSchema` instead. */
    BenefitDownloadablesUpdate$.inboundSchema = BenefitDownloadablesUpdate$inboundSchema;
    /** @deprecated use `BenefitDownloadablesUpdate$outboundSchema` instead. */
    BenefitDownloadablesUpdate$.outboundSchema = BenefitDownloadablesUpdate$outboundSchema;
})(BenefitDownloadablesUpdate$ || (BenefitDownloadablesUpdate$ = {}));
export function benefitDownloadablesUpdateToJSON(benefitDownloadablesUpdate) {
    return JSON.stringify(BenefitDownloadablesUpdate$outboundSchema.parse(benefitDownloadablesUpdate));
}
export function benefitDownloadablesUpdateFromJSON(jsonString) {
    return safeParse(jsonString, (x) => BenefitDownloadablesUpdate$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'BenefitDownloadablesUpdate' from JSON`);
}
//# sourceMappingURL=benefitdownloadablesupdate.js.map