"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.ListResourceCustomerBenefitGrant$ = exports.ListResourceCustomerBenefitGrant$outboundSchema = exports.ListResourceCustomerBenefitGrant$inboundSchema = void 0;
exports.listResourceCustomerBenefitGrantToJSON = listResourceCustomerBenefitGrantToJSON;
exports.listResourceCustomerBenefitGrantFromJSON = listResourceCustomerBenefitGrantFromJSON;
const z = __importStar(require("zod"));
const schemas_js_1 = require("../../lib/schemas.js");
const customerbenefitgrant_js_1 = require("./customerbenefitgrant.js");
const pagination_js_1 = require("./pagination.js");
/** @internal */
exports.ListResourceCustomerBenefitGrant$inboundSchema = z.object({
    items: z.array(customerbenefitgrant_js_1.CustomerBenefitGrant$inboundSchema),
    pagination: pagination_js_1.Pagination$inboundSchema,
});
/** @internal */
exports.ListResourceCustomerBenefitGrant$outboundSchema = z.object({
    items: z.array(customerbenefitgrant_js_1.CustomerBenefitGrant$outboundSchema),
    pagination: pagination_js_1.Pagination$outboundSchema,
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
var ListResourceCustomerBenefitGrant$;
(function (ListResourceCustomerBenefitGrant$) {
    /** @deprecated use `ListResourceCustomerBenefitGrant$inboundSchema` instead. */
    ListResourceCustomerBenefitGrant$.inboundSchema = exports.ListResourceCustomerBenefitGrant$inboundSchema;
    /** @deprecated use `ListResourceCustomerBenefitGrant$outboundSchema` instead. */
    ListResourceCustomerBenefitGrant$.outboundSchema = exports.ListResourceCustomerBenefitGrant$outboundSchema;
})(ListResourceCustomerBenefitGrant$ || (exports.ListResourceCustomerBenefitGrant$ = ListResourceCustomerBenefitGrant$ = {}));
function listResourceCustomerBenefitGrantToJSON(listResourceCustomerBenefitGrant) {
    return JSON.stringify(exports.ListResourceCustomerBenefitGrant$outboundSchema.parse(listResourceCustomerBenefitGrant));
}
function listResourceCustomerBenefitGrantFromJSON(jsonString) {
    return (0, schemas_js_1.safeParse)(jsonString, (x) => exports.ListResourceCustomerBenefitGrant$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ListResourceCustomerBenefitGrant' from JSON`);
}
//# sourceMappingURL=listresourcecustomerbenefitgrant.js.map