"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.CustomerPortalCustomersGetPaymentMethodsResponse$ = exports.CustomerPortalCustomersGetPaymentMethodsResponse$outboundSchema = exports.CustomerPortalCustomersGetPaymentMethodsResponse$inboundSchema = exports.CustomerPortalCustomersGetPaymentMethodsRequest$ = exports.CustomerPortalCustomersGetPaymentMethodsRequest$outboundSchema = exports.CustomerPortalCustomersGetPaymentMethodsRequest$inboundSchema = exports.CustomerPortalCustomersGetPaymentMethodsSecurity$ = exports.CustomerPortalCustomersGetPaymentMethodsSecurity$outboundSchema = exports.CustomerPortalCustomersGetPaymentMethodsSecurity$inboundSchema = void 0;
exports.customerPortalCustomersGetPaymentMethodsSecurityToJSON = customerPortalCustomersGetPaymentMethodsSecurityToJSON;
exports.customerPortalCustomersGetPaymentMethodsSecurityFromJSON = customerPortalCustomersGetPaymentMethodsSecurityFromJSON;
exports.customerPortalCustomersGetPaymentMethodsRequestToJSON = customerPortalCustomersGetPaymentMethodsRequestToJSON;
exports.customerPortalCustomersGetPaymentMethodsRequestFromJSON = customerPortalCustomersGetPaymentMethodsRequestFromJSON;
exports.customerPortalCustomersGetPaymentMethodsResponseToJSON = customerPortalCustomersGetPaymentMethodsResponseToJSON;
exports.customerPortalCustomersGetPaymentMethodsResponseFromJSON = customerPortalCustomersGetPaymentMethodsResponseFromJSON;
const z = __importStar(require("zod"));
const primitives_js_1 = require("../../lib/primitives.js");
const schemas_js_1 = require("../../lib/schemas.js");
const listresourceunionpaymentmethodcardpaymentmethodgeneric_js_1 = require("../components/listresourceunionpaymentmethodcardpaymentmethodgeneric.js");
/** @internal */
exports.CustomerPortalCustomersGetPaymentMethodsSecurity$inboundSchema = z.object({
    customer_session: z.string(),
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        "customer_session": "customerSession",
    });
});
/** @internal */
exports.CustomerPortalCustomersGetPaymentMethodsSecurity$outboundSchema = z.object({
    customerSession: z.string(),
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        customerSession: "customer_session",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
var CustomerPortalCustomersGetPaymentMethodsSecurity$;
(function (CustomerPortalCustomersGetPaymentMethodsSecurity$) {
    /** @deprecated use `CustomerPortalCustomersGetPaymentMethodsSecurity$inboundSchema` instead. */
    CustomerPortalCustomersGetPaymentMethodsSecurity$.inboundSchema = exports.CustomerPortalCustomersGetPaymentMethodsSecurity$inboundSchema;
    /** @deprecated use `CustomerPortalCustomersGetPaymentMethodsSecurity$outboundSchema` instead. */
    CustomerPortalCustomersGetPaymentMethodsSecurity$.outboundSchema = exports.CustomerPortalCustomersGetPaymentMethodsSecurity$outboundSchema;
})(CustomerPortalCustomersGetPaymentMethodsSecurity$ || (exports.CustomerPortalCustomersGetPaymentMethodsSecurity$ = CustomerPortalCustomersGetPaymentMethodsSecurity$ = {}));
function customerPortalCustomersGetPaymentMethodsSecurityToJSON(customerPortalCustomersGetPaymentMethodsSecurity) {
    return JSON.stringify(exports.CustomerPortalCustomersGetPaymentMethodsSecurity$outboundSchema.parse(customerPortalCustomersGetPaymentMethodsSecurity));
}
function customerPortalCustomersGetPaymentMethodsSecurityFromJSON(jsonString) {
    return (0, schemas_js_1.safeParse)(jsonString, (x) => exports.CustomerPortalCustomersGetPaymentMethodsSecurity$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'CustomerPortalCustomersGetPaymentMethodsSecurity' from JSON`);
}
/** @internal */
exports.CustomerPortalCustomersGetPaymentMethodsRequest$inboundSchema = z.object({
    page: z.number().int().default(1),
    limit: z.number().int().default(10),
});
/** @internal */
exports.CustomerPortalCustomersGetPaymentMethodsRequest$outboundSchema = z.object({
    page: z.number().int().default(1),
    limit: z.number().int().default(10),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
var CustomerPortalCustomersGetPaymentMethodsRequest$;
(function (CustomerPortalCustomersGetPaymentMethodsRequest$) {
    /** @deprecated use `CustomerPortalCustomersGetPaymentMethodsRequest$inboundSchema` instead. */
    CustomerPortalCustomersGetPaymentMethodsRequest$.inboundSchema = exports.CustomerPortalCustomersGetPaymentMethodsRequest$inboundSchema;
    /** @deprecated use `CustomerPortalCustomersGetPaymentMethodsRequest$outboundSchema` instead. */
    CustomerPortalCustomersGetPaymentMethodsRequest$.outboundSchema = exports.CustomerPortalCustomersGetPaymentMethodsRequest$outboundSchema;
})(CustomerPortalCustomersGetPaymentMethodsRequest$ || (exports.CustomerPortalCustomersGetPaymentMethodsRequest$ = CustomerPortalCustomersGetPaymentMethodsRequest$ = {}));
function customerPortalCustomersGetPaymentMethodsRequestToJSON(customerPortalCustomersGetPaymentMethodsRequest) {
    return JSON.stringify(exports.CustomerPortalCustomersGetPaymentMethodsRequest$outboundSchema.parse(customerPortalCustomersGetPaymentMethodsRequest));
}
function customerPortalCustomersGetPaymentMethodsRequestFromJSON(jsonString) {
    return (0, schemas_js_1.safeParse)(jsonString, (x) => exports.CustomerPortalCustomersGetPaymentMethodsRequest$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'CustomerPortalCustomersGetPaymentMethodsRequest' from JSON`);
}
/** @internal */
exports.CustomerPortalCustomersGetPaymentMethodsResponse$inboundSchema = z.object({
    Result: listresourceunionpaymentmethodcardpaymentmethodgeneric_js_1.ListResourceUnionPaymentMethodCardPaymentMethodGeneric$inboundSchema,
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        "Result": "result",
    });
});
/** @internal */
exports.CustomerPortalCustomersGetPaymentMethodsResponse$outboundSchema = z.object({
    result: listresourceunionpaymentmethodcardpaymentmethodgeneric_js_1.ListResourceUnionPaymentMethodCardPaymentMethodGeneric$outboundSchema,
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        result: "Result",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
var CustomerPortalCustomersGetPaymentMethodsResponse$;
(function (CustomerPortalCustomersGetPaymentMethodsResponse$) {
    /** @deprecated use `CustomerPortalCustomersGetPaymentMethodsResponse$inboundSchema` instead. */
    CustomerPortalCustomersGetPaymentMethodsResponse$.inboundSchema = exports.CustomerPortalCustomersGetPaymentMethodsResponse$inboundSchema;
    /** @deprecated use `CustomerPortalCustomersGetPaymentMethodsResponse$outboundSchema` instead. */
    CustomerPortalCustomersGetPaymentMethodsResponse$.outboundSchema = exports.CustomerPortalCustomersGetPaymentMethodsResponse$outboundSchema;
})(CustomerPortalCustomersGetPaymentMethodsResponse$ || (exports.CustomerPortalCustomersGetPaymentMethodsResponse$ = CustomerPortalCustomersGetPaymentMethodsResponse$ = {}));
function customerPortalCustomersGetPaymentMethodsResponseToJSON(customerPortalCustomersGetPaymentMethodsResponse) {
    return JSON.stringify(exports.CustomerPortalCustomersGetPaymentMethodsResponse$outboundSchema.parse(customerPortalCustomersGetPaymentMethodsResponse));
}
function customerPortalCustomersGetPaymentMethodsResponseFromJSON(jsonString) {
    return (0, schemas_js_1.safeParse)(jsonString, (x) => exports.CustomerPortalCustomersGetPaymentMethodsResponse$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'CustomerPortalCustomersGetPaymentMethodsResponse' from JSON`);
}
//# sourceMappingURL=customerportalcustomersgetpaymentmethods.js.map