/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { BenefitDownloadablesSubscriberProperties$inboundSchema, BenefitDownloadablesSubscriberProperties$outboundSchema, } from "./benefitdownloadablessubscriberproperties.js";
import { Organization$inboundSchema, Organization$outboundSchema, } from "./organization.js";
/** @internal */
export const BenefitDownloadablesSubscriber$inboundSchema = z.object({
    created_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
    modified_at: z.nullable(z.string().datetime({ offset: true }).transform(v => new Date(v))),
    id: z.string(),
    type: z.literal("downloadables").optional(),
    description: z.string(),
    selectable: z.boolean(),
    deletable: z.boolean(),
    organization_id: z.string(),
    organization: Organization$inboundSchema,
    properties: BenefitDownloadablesSubscriberProperties$inboundSchema,
}).transform((v) => {
    return remap$(v, {
        "created_at": "createdAt",
        "modified_at": "modifiedAt",
        "organization_id": "organizationId",
    });
});
/** @internal */
export const BenefitDownloadablesSubscriber$outboundSchema = z.object({
    createdAt: z.date().transform(v => v.toISOString()),
    modifiedAt: z.nullable(z.date().transform(v => v.toISOString())),
    id: z.string(),
    type: z.literal("downloadables").default("downloadables"),
    description: z.string(),
    selectable: z.boolean(),
    deletable: z.boolean(),
    organizationId: z.string(),
    organization: Organization$outboundSchema,
    properties: BenefitDownloadablesSubscriberProperties$outboundSchema,
}).transform((v) => {
    return remap$(v, {
        createdAt: "created_at",
        modifiedAt: "modified_at",
        organizationId: "organization_id",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var BenefitDownloadablesSubscriber$;
(function (BenefitDownloadablesSubscriber$) {
    /** @deprecated use `BenefitDownloadablesSubscriber$inboundSchema` instead. */
    BenefitDownloadablesSubscriber$.inboundSchema = BenefitDownloadablesSubscriber$inboundSchema;
    /** @deprecated use `BenefitDownloadablesSubscriber$outboundSchema` instead. */
    BenefitDownloadablesSubscriber$.outboundSchema = BenefitDownloadablesSubscriber$outboundSchema;
})(BenefitDownloadablesSubscriber$ || (BenefitDownloadablesSubscriber$ = {}));
export function benefitDownloadablesSubscriberToJSON(benefitDownloadablesSubscriber) {
    return JSON.stringify(BenefitDownloadablesSubscriber$outboundSchema.parse(benefitDownloadablesSubscriber));
}
export function benefitDownloadablesSubscriberFromJSON(jsonString) {
    return safeParse(jsonString, (x) => BenefitDownloadablesSubscriber$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'BenefitDownloadablesSubscriber' from JSON`);
}
//# sourceMappingURL=benefitdownloadablessubscriber.js.map