/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { externalOrganizationsList } from "../funcs/externalOrganizationsList.js";
import { ClientSDK } from "../lib/sdks.js";
import { unwrapResultIterator } from "../types/operations.js";
export class ExternalOrganizations extends ClientSDK {
    /**
     * List External Organizations
     *
     * @remarks
     * List external organizations.
     *
     * **Scopes**: `external_organizations:read`
     */
    async list(request, options) {
        return unwrapResultIterator(externalOrganizationsList(this, request, options));
    }
}
//# sourceMappingURL=externalorganizations.js.map