/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
/** @internal */
export const SubscriptionUser$inboundSchema = z.object({
    id: z.string(),
    email: z.string(),
    public_name: z.string(),
    avatar_url: z.nullable(z.string()).optional(),
    github_username: z.nullable(z.string()).optional(),
}).transform((v) => {
    return remap$(v, {
        "public_name": "publicName",
        "avatar_url": "avatarUrl",
        "github_username": "githubUsername",
    });
});
/** @internal */
export const SubscriptionUser$outboundSchema = z.object({
    id: z.string(),
    email: z.string(),
    publicName: z.string(),
    avatarUrl: z.nullable(z.string()).optional(),
    githubUsername: z.nullable(z.string()).optional(),
}).transform((v) => {
    return remap$(v, {
        publicName: "public_name",
        avatarUrl: "avatar_url",
        githubUsername: "github_username",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var SubscriptionUser$;
(function (SubscriptionUser$) {
    /** @deprecated use `SubscriptionUser$inboundSchema` instead. */
    SubscriptionUser$.inboundSchema = SubscriptionUser$inboundSchema;
    /** @deprecated use `SubscriptionUser$outboundSchema` instead. */
    SubscriptionUser$.outboundSchema = SubscriptionUser$outboundSchema;
})(SubscriptionUser$ || (SubscriptionUser$ = {}));
export function subscriptionUserToJSON(subscriptionUser) {
    return JSON.stringify(SubscriptionUser$outboundSchema.parse(subscriptionUser));
}
export function subscriptionUserFromJSON(jsonString) {
    return safeParse(jsonString, (x) => SubscriptionUser$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'SubscriptionUser' from JSON`);
}
//# sourceMappingURL=subscriptionuser.js.map