"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.BenefitGitHubRepositoryUpdate$ = exports.BenefitGitHubRepositoryUpdate$outboundSchema = exports.BenefitGitHubRepositoryUpdate$inboundSchema = void 0;
exports.benefitGitHubRepositoryUpdateToJSON = benefitGitHubRepositoryUpdateToJSON;
exports.benefitGitHubRepositoryUpdateFromJSON = benefitGitHubRepositoryUpdateFromJSON;
const z = __importStar(require("zod"));
const schemas_js_1 = require("../../lib/schemas.js");
const benefitgithubrepositorycreateproperties_js_1 = require("./benefitgithubrepositorycreateproperties.js");
/** @internal */
exports.BenefitGitHubRepositoryUpdate$inboundSchema = z.object({
    description: z.nullable(z.string()).optional(),
    type: z.literal("github_repository").optional(),
    properties: z.nullable(benefitgithubrepositorycreateproperties_js_1.BenefitGitHubRepositoryCreateProperties$inboundSchema)
        .optional(),
});
/** @internal */
exports.BenefitGitHubRepositoryUpdate$outboundSchema = z.object({
    description: z.nullable(z.string()).optional(),
    type: z.literal("github_repository").default("github_repository"),
    properties: z.nullable(benefitgithubrepositorycreateproperties_js_1.BenefitGitHubRepositoryCreateProperties$outboundSchema)
        .optional(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
var BenefitGitHubRepositoryUpdate$;
(function (BenefitGitHubRepositoryUpdate$) {
    /** @deprecated use `BenefitGitHubRepositoryUpdate$inboundSchema` instead. */
    BenefitGitHubRepositoryUpdate$.inboundSchema = exports.BenefitGitHubRepositoryUpdate$inboundSchema;
    /** @deprecated use `BenefitGitHubRepositoryUpdate$outboundSchema` instead. */
    BenefitGitHubRepositoryUpdate$.outboundSchema = exports.BenefitGitHubRepositoryUpdate$outboundSchema;
})(BenefitGitHubRepositoryUpdate$ || (exports.BenefitGitHubRepositoryUpdate$ = BenefitGitHubRepositoryUpdate$ = {}));
function benefitGitHubRepositoryUpdateToJSON(benefitGitHubRepositoryUpdate) {
    return JSON.stringify(exports.BenefitGitHubRepositoryUpdate$outboundSchema.parse(benefitGitHubRepositoryUpdate));
}
function benefitGitHubRepositoryUpdateFromJSON(jsonString) {
    return (0, schemas_js_1.safeParse)(jsonString, (x) => exports.BenefitGitHubRepositoryUpdate$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'BenefitGitHubRepositoryUpdate' from JSON`);
}
//# sourceMappingURL=benefitgithubrepositoryupdate.js.map