/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { BenefitType$inboundSchema, BenefitType$outboundSchema, } from "./benefittype.js";
/** @internal */
export const BenefitBase$inboundSchema = z.object({
    created_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
    modified_at: z.nullable(z.string().datetime({ offset: true }).transform(v => new Date(v))),
    id: z.string(),
    type: BenefitType$inboundSchema,
    description: z.string(),
    selectable: z.boolean(),
    deletable: z.boolean(),
    organization_id: z.string(),
}).transform((v) => {
    return remap$(v, {
        "created_at": "createdAt",
        "modified_at": "modifiedAt",
        "organization_id": "organizationId",
    });
});
/** @internal */
export const BenefitBase$outboundSchema = z.object({
    createdAt: z.date().transform(v => v.toISOString()),
    modifiedAt: z.nullable(z.date().transform(v => v.toISOString())),
    id: z.string(),
    type: BenefitType$outboundSchema,
    description: z.string(),
    selectable: z.boolean(),
    deletable: z.boolean(),
    organizationId: z.string(),
}).transform((v) => {
    return remap$(v, {
        createdAt: "created_at",
        modifiedAt: "modified_at",
        organizationId: "organization_id",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var BenefitBase$;
(function (BenefitBase$) {
    /** @deprecated use `BenefitBase$inboundSchema` instead. */
    BenefitBase$.inboundSchema = BenefitBase$inboundSchema;
    /** @deprecated use `BenefitBase$outboundSchema` instead. */
    BenefitBase$.outboundSchema = BenefitBase$outboundSchema;
})(BenefitBase$ || (BenefitBase$ = {}));
export function benefitBaseToJSON(benefitBase) {
    return JSON.stringify(BenefitBase$outboundSchema.parse(benefitBase));
}
export function benefitBaseFromJSON(jsonString) {
    return safeParse(jsonString, (x) => BenefitBase$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'BenefitBase' from JSON`);
}
//# sourceMappingURL=benefitbase.js.map