/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { ordersGet } from "../funcs/ordersGet.js";
import { ordersInvoice } from "../funcs/ordersInvoice.js";
import { ordersList } from "../funcs/ordersList.js";
import { ClientSDK } from "../lib/sdks.js";
import { unwrapAsync } from "../types/fp.js";
import { unwrapResultIterator } from "../types/operations.js";
export class Orders extends ClientSDK {
    /**
     * List Orders
     *
     * @remarks
     * List orders.
     *
     * **Scopes**: `orders:read`
     */
    async list(request, options) {
        return unwrapResultIterator(ordersList(this, request, options));
    }
    /**
     * Get Order
     *
     * @remarks
     * Get an order by ID.
     *
     * **Scopes**: `orders:read`
     */
    async get(request, options) {
        return unwrapAsync(ordersGet(this, request, options));
    }
    /**
     * Get Order Invoice
     *
     * @remarks
     * Get an order's invoice data.
     *
     * **Scopes**: `orders:read`
     */
    async invoice(request, options) {
        return unwrapAsync(ordersInvoice(this, request, options));
    }
}
//# sourceMappingURL=orders.js.map