"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.AuthorizationCodeTokenRequest$ = exports.AuthorizationCodeTokenRequest$outboundSchema = exports.AuthorizationCodeTokenRequest$inboundSchema = void 0;
exports.authorizationCodeTokenRequestToJSON = authorizationCodeTokenRequestToJSON;
exports.authorizationCodeTokenRequestFromJSON = authorizationCodeTokenRequestFromJSON;
const z = __importStar(require("zod"));
const primitives_js_1 = require("../../lib/primitives.js");
const schemas_js_1 = require("../../lib/schemas.js");
/** @internal */
exports.AuthorizationCodeTokenRequest$inboundSchema = z.object({
    grant_type: z.literal("authorization_code").optional(),
    client_id: z.string(),
    client_secret: z.string(),
    code: z.string(),
    redirect_uri: z.string(),
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        "grant_type": "grantType",
        "client_id": "clientId",
        "client_secret": "clientSecret",
        "redirect_uri": "redirectUri",
    });
});
/** @internal */
exports.AuthorizationCodeTokenRequest$outboundSchema = z.object({
    grantType: z.literal("authorization_code").default("authorization_code"),
    clientId: z.string(),
    clientSecret: z.string(),
    code: z.string(),
    redirectUri: z.string(),
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        grantType: "grant_type",
        clientId: "client_id",
        clientSecret: "client_secret",
        redirectUri: "redirect_uri",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
var AuthorizationCodeTokenRequest$;
(function (AuthorizationCodeTokenRequest$) {
    /** @deprecated use `AuthorizationCodeTokenRequest$inboundSchema` instead. */
    AuthorizationCodeTokenRequest$.inboundSchema = exports.AuthorizationCodeTokenRequest$inboundSchema;
    /** @deprecated use `AuthorizationCodeTokenRequest$outboundSchema` instead. */
    AuthorizationCodeTokenRequest$.outboundSchema = exports.AuthorizationCodeTokenRequest$outboundSchema;
})(AuthorizationCodeTokenRequest$ || (exports.AuthorizationCodeTokenRequest$ = AuthorizationCodeTokenRequest$ = {}));
function authorizationCodeTokenRequestToJSON(authorizationCodeTokenRequest) {
    return JSON.stringify(exports.AuthorizationCodeTokenRequest$outboundSchema.parse(authorizationCodeTokenRequest));
}
function authorizationCodeTokenRequestFromJSON(jsonString) {
    return (0, schemas_js_1.safeParse)(jsonString, (x) => exports.AuthorizationCodeTokenRequest$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'AuthorizationCodeTokenRequest' from JSON`);
}
//# sourceMappingURL=authorizationcodetokenrequest.js.map