/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { BenefitGitHubRepositoryProperties$inboundSchema, BenefitGitHubRepositoryProperties$outboundSchema, } from "./benefitgithubrepositoryproperties.js";
/** @internal */
export const BenefitGitHubRepository$inboundSchema = z.object({
    created_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
    modified_at: z.nullable(z.string().datetime({ offset: true }).transform(v => new Date(v))),
    id: z.string(),
    type: z.literal("github_repository").optional(),
    description: z.string(),
    selectable: z.boolean(),
    deletable: z.boolean(),
    organization_id: z.string(),
    properties: BenefitGitHubRepositoryProperties$inboundSchema,
}).transform((v) => {
    return remap$(v, {
        "created_at": "createdAt",
        "modified_at": "modifiedAt",
        "organization_id": "organizationId",
    });
});
/** @internal */
export const BenefitGitHubRepository$outboundSchema = z.object({
    createdAt: z.date().transform(v => v.toISOString()),
    modifiedAt: z.nullable(z.date().transform(v => v.toISOString())),
    id: z.string(),
    type: z.literal("github_repository").default("github_repository"),
    description: z.string(),
    selectable: z.boolean(),
    deletable: z.boolean(),
    organizationId: z.string(),
    properties: BenefitGitHubRepositoryProperties$outboundSchema,
}).transform((v) => {
    return remap$(v, {
        createdAt: "created_at",
        modifiedAt: "modified_at",
        organizationId: "organization_id",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var BenefitGitHubRepository$;
(function (BenefitGitHubRepository$) {
    /** @deprecated use `BenefitGitHubRepository$inboundSchema` instead. */
    BenefitGitHubRepository$.inboundSchema = BenefitGitHubRepository$inboundSchema;
    /** @deprecated use `BenefitGitHubRepository$outboundSchema` instead. */
    BenefitGitHubRepository$.outboundSchema = BenefitGitHubRepository$outboundSchema;
})(BenefitGitHubRepository$ || (BenefitGitHubRepository$ = {}));
export function benefitGitHubRepositoryToJSON(benefitGitHubRepository) {
    return JSON.stringify(BenefitGitHubRepository$outboundSchema.parse(benefitGitHubRepository));
}
export function benefitGitHubRepositoryFromJSON(jsonString) {
    return safeParse(jsonString, (x) => BenefitGitHubRepository$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'BenefitGitHubRepository' from JSON`);
}
//# sourceMappingURL=benefitgithubrepository.js.map