/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { CheckoutPriceCreate$inboundSchema, CheckoutPriceCreate$outboundSchema, } from "./checkoutpricecreate.js";
import { CheckoutProductCreate$inboundSchema, CheckoutProductCreate$outboundSchema, } from "./checkoutproductcreate.js";
import { CheckoutProductsCreate$inboundSchema, CheckoutProductsCreate$outboundSchema, } from "./checkoutproductscreate.js";
/** @internal */
export const CheckoutCreate$inboundSchema = z.union([
    CheckoutProductsCreate$inboundSchema,
    CheckoutProductCreate$inboundSchema,
    CheckoutPriceCreate$inboundSchema,
]);
/** @internal */
export const CheckoutCreate$outboundSchema = z.union([
    CheckoutProductsCreate$outboundSchema,
    CheckoutProductCreate$outboundSchema,
    CheckoutPriceCreate$outboundSchema,
]);
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var CheckoutCreate$;
(function (CheckoutCreate$) {
    /** @deprecated use `CheckoutCreate$inboundSchema` instead. */
    CheckoutCreate$.inboundSchema = CheckoutCreate$inboundSchema;
    /** @deprecated use `CheckoutCreate$outboundSchema` instead. */
    CheckoutCreate$.outboundSchema = CheckoutCreate$outboundSchema;
})(CheckoutCreate$ || (CheckoutCreate$ = {}));
export function checkoutCreateToJSON(checkoutCreate) {
    return JSON.stringify(CheckoutCreate$outboundSchema.parse(checkoutCreate));
}
export function checkoutCreateFromJSON(jsonString) {
    return safeParse(jsonString, (x) => CheckoutCreate$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'CheckoutCreate' from JSON`);
}
//# sourceMappingURL=checkoutcreate.js.map