"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.WebhookCustomerDeletedPayload$ = exports.WebhookCustomerDeletedPayload$outboundSchema = exports.WebhookCustomerDeletedPayload$inboundSchema = void 0;
exports.webhookCustomerDeletedPayloadToJSON = webhookCustomerDeletedPayloadToJSON;
exports.webhookCustomerDeletedPayloadFromJSON = webhookCustomerDeletedPayloadFromJSON;
const z = __importStar(require("zod"));
const schemas_js_1 = require("../../lib/schemas.js");
const customer_js_1 = require("./customer.js");
/** @internal */
exports.WebhookCustomerDeletedPayload$inboundSchema = z.object({
    type: z.literal("customer.deleted").optional(),
    data: customer_js_1.Customer$inboundSchema,
});
/** @internal */
exports.WebhookCustomerDeletedPayload$outboundSchema = z.object({
    type: z.literal("customer.deleted").default("customer.deleted"),
    data: customer_js_1.Customer$outboundSchema,
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
var WebhookCustomerDeletedPayload$;
(function (WebhookCustomerDeletedPayload$) {
    /** @deprecated use `WebhookCustomerDeletedPayload$inboundSchema` instead. */
    WebhookCustomerDeletedPayload$.inboundSchema = exports.WebhookCustomerDeletedPayload$inboundSchema;
    /** @deprecated use `WebhookCustomerDeletedPayload$outboundSchema` instead. */
    WebhookCustomerDeletedPayload$.outboundSchema = exports.WebhookCustomerDeletedPayload$outboundSchema;
})(WebhookCustomerDeletedPayload$ || (exports.WebhookCustomerDeletedPayload$ = WebhookCustomerDeletedPayload$ = {}));
function webhookCustomerDeletedPayloadToJSON(webhookCustomerDeletedPayload) {
    return JSON.stringify(exports.WebhookCustomerDeletedPayload$outboundSchema.parse(webhookCustomerDeletedPayload));
}
function webhookCustomerDeletedPayloadFromJSON(jsonString) {
    return (0, schemas_js_1.safeParse)(jsonString, (x) => exports.WebhookCustomerDeletedPayload$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'WebhookCustomerDeletedPayload' from JSON`);
}
//# sourceMappingURL=webhookcustomerdeletedpayload.js.map