/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { BenefitLicenseKeysSubscriberProperties$inboundSchema, BenefitLicenseKeysSubscriberProperties$outboundSchema, } from "./benefitlicensekeyssubscriberproperties.js";
import { Organization$inboundSchema, Organization$outboundSchema, } from "./organization.js";
/** @internal */
export const BenefitLicenseKeysSubscriber$inboundSchema = z.object({
    created_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
    modified_at: z.nullable(z.string().datetime({ offset: true }).transform(v => new Date(v))),
    id: z.string(),
    type: z.literal("license_keys").optional(),
    description: z.string(),
    selectable: z.boolean(),
    deletable: z.boolean(),
    organization_id: z.string(),
    organization: Organization$inboundSchema,
    properties: BenefitLicenseKeysSubscriberProperties$inboundSchema,
}).transform((v) => {
    return remap$(v, {
        "created_at": "createdAt",
        "modified_at": "modifiedAt",
        "organization_id": "organizationId",
    });
});
/** @internal */
export const BenefitLicenseKeysSubscriber$outboundSchema = z.object({
    createdAt: z.date().transform(v => v.toISOString()),
    modifiedAt: z.nullable(z.date().transform(v => v.toISOString())),
    id: z.string(),
    type: z.literal("license_keys").default("license_keys"),
    description: z.string(),
    selectable: z.boolean(),
    deletable: z.boolean(),
    organizationId: z.string(),
    organization: Organization$outboundSchema,
    properties: BenefitLicenseKeysSubscriberProperties$outboundSchema,
}).transform((v) => {
    return remap$(v, {
        createdAt: "created_at",
        modifiedAt: "modified_at",
        organizationId: "organization_id",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var BenefitLicenseKeysSubscriber$;
(function (BenefitLicenseKeysSubscriber$) {
    /** @deprecated use `BenefitLicenseKeysSubscriber$inboundSchema` instead. */
    BenefitLicenseKeysSubscriber$.inboundSchema = BenefitLicenseKeysSubscriber$inboundSchema;
    /** @deprecated use `BenefitLicenseKeysSubscriber$outboundSchema` instead. */
    BenefitLicenseKeysSubscriber$.outboundSchema = BenefitLicenseKeysSubscriber$outboundSchema;
})(BenefitLicenseKeysSubscriber$ || (BenefitLicenseKeysSubscriber$ = {}));
export function benefitLicenseKeysSubscriberToJSON(benefitLicenseKeysSubscriber) {
    return JSON.stringify(BenefitLicenseKeysSubscriber$outboundSchema.parse(benefitLicenseKeysSubscriber));
}
export function benefitLicenseKeysSubscriberFromJSON(jsonString) {
    return safeParse(jsonString, (x) => BenefitLicenseKeysSubscriber$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'BenefitLicenseKeysSubscriber' from JSON`);
}
//# sourceMappingURL=benefitlicensekeyssubscriber.js.map