/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
/** @internal */
export const RepositoryProfileSettings$inboundSchema = z.object({
    description: z.nullable(z.string()).optional(),
    cover_image_url: z.nullable(z.string()).optional(),
    featured_organizations: z.nullable(z.array(z.string())).optional(),
    highlighted_subscription_tiers: z.nullable(z.array(z.string())).optional(),
    links: z.nullable(z.array(z.string())).optional(),
}).transform((v) => {
    return remap$(v, {
        "cover_image_url": "coverImageUrl",
        "featured_organizations": "featuredOrganizations",
        "highlighted_subscription_tiers": "highlightedSubscriptionTiers",
    });
});
/** @internal */
export const RepositoryProfileSettings$outboundSchema = z.object({
    description: z.nullable(z.string()).optional(),
    coverImageUrl: z.nullable(z.string()).optional(),
    featuredOrganizations: z.nullable(z.array(z.string())).optional(),
    highlightedSubscriptionTiers: z.nullable(z.array(z.string())).optional(),
    links: z.nullable(z.array(z.string())).optional(),
}).transform((v) => {
    return remap$(v, {
        coverImageUrl: "cover_image_url",
        featuredOrganizations: "featured_organizations",
        highlightedSubscriptionTiers: "highlighted_subscription_tiers",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var RepositoryProfileSettings$;
(function (RepositoryProfileSettings$) {
    /** @deprecated use `RepositoryProfileSettings$inboundSchema` instead. */
    RepositoryProfileSettings$.inboundSchema = RepositoryProfileSettings$inboundSchema;
    /** @deprecated use `RepositoryProfileSettings$outboundSchema` instead. */
    RepositoryProfileSettings$.outboundSchema = RepositoryProfileSettings$outboundSchema;
})(RepositoryProfileSettings$ || (RepositoryProfileSettings$ = {}));
export function repositoryProfileSettingsToJSON(repositoryProfileSettings) {
    return JSON.stringify(RepositoryProfileSettings$outboundSchema.parse(repositoryProfileSettings));
}
export function repositoryProfileSettingsFromJSON(jsonString) {
    return safeParse(jsonString, (x) => RepositoryProfileSettings$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'RepositoryProfileSettings' from JSON`);
}
//# sourceMappingURL=repositoryprofilesettings.js.map