/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const PledgeState = {
    Initiated: "initiated",
    Created: "created",
    Pending: "pending",
    Refunded: "refunded",
    Disputed: "disputed",
    ChargeDisputed: "charge_disputed",
    Cancelled: "cancelled",
};
/** @internal */
export const PledgeState$inboundSchema = z
    .nativeEnum(PledgeState);
/** @internal */
export const PledgeState$outboundSchema = PledgeState$inboundSchema;
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var PledgeState$;
(function (PledgeState$) {
    /** @deprecated use `PledgeState$inboundSchema` instead. */
    PledgeState$.inboundSchema = PledgeState$inboundSchema;
    /** @deprecated use `PledgeState$outboundSchema` instead. */
    PledgeState$.outboundSchema = PledgeState$outboundSchema;
})(PledgeState$ || (PledgeState$ = {}));
//# sourceMappingURL=pledgestate.js.map