/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
/** @internal */
export const PaymentMethodCardData$inboundSchema = z.object({
    brand: z.string(),
    last4: z.string(),
    exp_month: z.number().int(),
    exp_year: z.number().int(),
    wallet: z.nullable(z.string()).optional(),
}).transform((v) => {
    return remap$(v, {
        "exp_month": "expMonth",
        "exp_year": "expYear",
    });
});
/** @internal */
export const PaymentMethodCardData$outboundSchema = z.object({
    brand: z.string(),
    last4: z.string(),
    expMonth: z.number().int(),
    expYear: z.number().int(),
    wallet: z.nullable(z.string()).optional(),
}).transform((v) => {
    return remap$(v, {
        expMonth: "exp_month",
        expYear: "exp_year",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var PaymentMethodCardData$;
(function (PaymentMethodCardData$) {
    /** @deprecated use `PaymentMethodCardData$inboundSchema` instead. */
    PaymentMethodCardData$.inboundSchema = PaymentMethodCardData$inboundSchema;
    /** @deprecated use `PaymentMethodCardData$outboundSchema` instead. */
    PaymentMethodCardData$.outboundSchema = PaymentMethodCardData$outboundSchema;
})(PaymentMethodCardData$ || (PaymentMethodCardData$ = {}));
export function paymentMethodCardDataToJSON(paymentMethodCardData) {
    return JSON.stringify(PaymentMethodCardData$outboundSchema.parse(paymentMethodCardData));
}
export function paymentMethodCardDataFromJSON(jsonString) {
    return safeParse(jsonString, (x) => PaymentMethodCardData$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'PaymentMethodCardData' from JSON`);
}
//# sourceMappingURL=paymentmethodcarddata.js.map