/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
/** @internal */
export const Author$inboundSchema = z
    .object({
    id: z.number().int(),
    login: z.string(),
    html_url: z.string(),
    avatar_url: z.string(),
}).transform((v) => {
    return remap$(v, {
        "html_url": "htmlUrl",
        "avatar_url": "avatarUrl",
    });
});
/** @internal */
export const Author$outboundSchema = z.object({
    id: z.number().int(),
    login: z.string(),
    htmlUrl: z.string(),
    avatarUrl: z.string(),
}).transform((v) => {
    return remap$(v, {
        htmlUrl: "html_url",
        avatarUrl: "avatar_url",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var Author$;
(function (Author$) {
    /** @deprecated use `Author$inboundSchema` instead. */
    Author$.inboundSchema = Author$inboundSchema;
    /** @deprecated use `Author$outboundSchema` instead. */
    Author$.outboundSchema = Author$outboundSchema;
})(Author$ || (Author$ = {}));
export function authorToJSON(author) {
    return JSON.stringify(Author$outboundSchema.parse(author));
}
export function authorFromJSON(jsonString) {
    return safeParse(jsonString, (x) => Author$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'Author' from JSON`);
}
//# sourceMappingURL=author.js.map