"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.CheckoutPriceCreate$ = exports.CheckoutPriceCreate$outboundSchema = exports.CheckoutPriceCreate$inboundSchema = exports.CheckoutPriceCreateCustomerMetadata$ = exports.CheckoutPriceCreateCustomerMetadata$outboundSchema = exports.CheckoutPriceCreateCustomerMetadata$inboundSchema = exports.CheckoutPriceCreateCustomFieldData$ = exports.CheckoutPriceCreateCustomFieldData$outboundSchema = exports.CheckoutPriceCreateCustomFieldData$inboundSchema = exports.CheckoutPriceCreateMetadata$ = exports.CheckoutPriceCreateMetadata$outboundSchema = exports.CheckoutPriceCreateMetadata$inboundSchema = void 0;
exports.checkoutPriceCreateMetadataToJSON = checkoutPriceCreateMetadataToJSON;
exports.checkoutPriceCreateMetadataFromJSON = checkoutPriceCreateMetadataFromJSON;
exports.checkoutPriceCreateCustomFieldDataToJSON = checkoutPriceCreateCustomFieldDataToJSON;
exports.checkoutPriceCreateCustomFieldDataFromJSON = checkoutPriceCreateCustomFieldDataFromJSON;
exports.checkoutPriceCreateCustomerMetadataToJSON = checkoutPriceCreateCustomerMetadataToJSON;
exports.checkoutPriceCreateCustomerMetadataFromJSON = checkoutPriceCreateCustomerMetadataFromJSON;
exports.checkoutPriceCreateToJSON = checkoutPriceCreateToJSON;
exports.checkoutPriceCreateFromJSON = checkoutPriceCreateFromJSON;
const z = __importStar(require("zod"));
const primitives_js_1 = require("../../lib/primitives.js");
const schemas_js_1 = require("../../lib/schemas.js");
const address_js_1 = require("./address.js");
/** @internal */
exports.CheckoutPriceCreateMetadata$inboundSchema = z.union([z.string(), z.number().int(), z.boolean()]);
/** @internal */
exports.CheckoutPriceCreateMetadata$outboundSchema = z.union([z.string(), z.number().int(), z.boolean()]);
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
var CheckoutPriceCreateMetadata$;
(function (CheckoutPriceCreateMetadata$) {
    /** @deprecated use `CheckoutPriceCreateMetadata$inboundSchema` instead. */
    CheckoutPriceCreateMetadata$.inboundSchema = exports.CheckoutPriceCreateMetadata$inboundSchema;
    /** @deprecated use `CheckoutPriceCreateMetadata$outboundSchema` instead. */
    CheckoutPriceCreateMetadata$.outboundSchema = exports.CheckoutPriceCreateMetadata$outboundSchema;
})(CheckoutPriceCreateMetadata$ || (exports.CheckoutPriceCreateMetadata$ = CheckoutPriceCreateMetadata$ = {}));
function checkoutPriceCreateMetadataToJSON(checkoutPriceCreateMetadata) {
    return JSON.stringify(exports.CheckoutPriceCreateMetadata$outboundSchema.parse(checkoutPriceCreateMetadata));
}
function checkoutPriceCreateMetadataFromJSON(jsonString) {
    return (0, schemas_js_1.safeParse)(jsonString, (x) => exports.CheckoutPriceCreateMetadata$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'CheckoutPriceCreateMetadata' from JSON`);
}
/** @internal */
exports.CheckoutPriceCreateCustomFieldData$inboundSchema = z.union([
    z.string(),
    z.number().int(),
    z.boolean(),
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
]);
/** @internal */
exports.CheckoutPriceCreateCustomFieldData$outboundSchema = z.union([
    z.string(),
    z.number().int(),
    z.boolean(),
    z.date().transform(v => v.toISOString()),
]);
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
var CheckoutPriceCreateCustomFieldData$;
(function (CheckoutPriceCreateCustomFieldData$) {
    /** @deprecated use `CheckoutPriceCreateCustomFieldData$inboundSchema` instead. */
    CheckoutPriceCreateCustomFieldData$.inboundSchema = exports.CheckoutPriceCreateCustomFieldData$inboundSchema;
    /** @deprecated use `CheckoutPriceCreateCustomFieldData$outboundSchema` instead. */
    CheckoutPriceCreateCustomFieldData$.outboundSchema = exports.CheckoutPriceCreateCustomFieldData$outboundSchema;
})(CheckoutPriceCreateCustomFieldData$ || (exports.CheckoutPriceCreateCustomFieldData$ = CheckoutPriceCreateCustomFieldData$ = {}));
function checkoutPriceCreateCustomFieldDataToJSON(checkoutPriceCreateCustomFieldData) {
    return JSON.stringify(exports.CheckoutPriceCreateCustomFieldData$outboundSchema.parse(checkoutPriceCreateCustomFieldData));
}
function checkoutPriceCreateCustomFieldDataFromJSON(jsonString) {
    return (0, schemas_js_1.safeParse)(jsonString, (x) => exports.CheckoutPriceCreateCustomFieldData$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'CheckoutPriceCreateCustomFieldData' from JSON`);
}
/** @internal */
exports.CheckoutPriceCreateCustomerMetadata$inboundSchema = z.union([z.string(), z.number().int(), z.boolean()]);
/** @internal */
exports.CheckoutPriceCreateCustomerMetadata$outboundSchema = z.union([z.string(), z.number().int(), z.boolean()]);
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
var CheckoutPriceCreateCustomerMetadata$;
(function (CheckoutPriceCreateCustomerMetadata$) {
    /** @deprecated use `CheckoutPriceCreateCustomerMetadata$inboundSchema` instead. */
    CheckoutPriceCreateCustomerMetadata$.inboundSchema = exports.CheckoutPriceCreateCustomerMetadata$inboundSchema;
    /** @deprecated use `CheckoutPriceCreateCustomerMetadata$outboundSchema` instead. */
    CheckoutPriceCreateCustomerMetadata$.outboundSchema = exports.CheckoutPriceCreateCustomerMetadata$outboundSchema;
})(CheckoutPriceCreateCustomerMetadata$ || (exports.CheckoutPriceCreateCustomerMetadata$ = CheckoutPriceCreateCustomerMetadata$ = {}));
function checkoutPriceCreateCustomerMetadataToJSON(checkoutPriceCreateCustomerMetadata) {
    return JSON.stringify(exports.CheckoutPriceCreateCustomerMetadata$outboundSchema.parse(checkoutPriceCreateCustomerMetadata));
}
function checkoutPriceCreateCustomerMetadataFromJSON(jsonString) {
    return (0, schemas_js_1.safeParse)(jsonString, (x) => exports.CheckoutPriceCreateCustomerMetadata$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'CheckoutPriceCreateCustomerMetadata' from JSON`);
}
/** @internal */
exports.CheckoutPriceCreate$inboundSchema = z.object({
    metadata: z.record(z.union([z.string(), z.number().int(), z.boolean()]))
        .optional(),
    custom_field_data: z.record(z.nullable(z.union([
        z.string(),
        z.number().int(),
        z.boolean(),
        z.string().datetime({ offset: true }).transform(v => new Date(v)),
    ]))).optional(),
    discount_id: z.nullable(z.string()).optional(),
    allow_discount_codes: z.boolean().default(true),
    amount: z.nullable(z.number().int()).optional(),
    customer_id: z.nullable(z.string()).optional(),
    customer_external_id: z.nullable(z.string()).optional(),
    customer_name: z.nullable(z.string()).optional(),
    customer_email: z.nullable(z.string()).optional(),
    customer_ip_address: z.nullable(z.string()).optional(),
    customer_billing_address: z.nullable(address_js_1.Address$inboundSchema).optional(),
    customer_tax_id: z.nullable(z.string()).optional(),
    customer_metadata: z.record(z.union([z.string(), z.number().int(), z.boolean()])).optional(),
    subscription_id: z.nullable(z.string()).optional(),
    success_url: z.nullable(z.string()).optional(),
    embed_origin: z.nullable(z.string()).optional(),
    product_price_id: z.string(),
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        "custom_field_data": "customFieldData",
        "discount_id": "discountId",
        "allow_discount_codes": "allowDiscountCodes",
        "customer_id": "customerId",
        "customer_external_id": "customerExternalId",
        "customer_name": "customerName",
        "customer_email": "customerEmail",
        "customer_ip_address": "customerIpAddress",
        "customer_billing_address": "customerBillingAddress",
        "customer_tax_id": "customerTaxId",
        "customer_metadata": "customerMetadata",
        "subscription_id": "subscriptionId",
        "success_url": "successUrl",
        "embed_origin": "embedOrigin",
        "product_price_id": "productPriceId",
    });
});
/** @internal */
exports.CheckoutPriceCreate$outboundSchema = z.object({
    metadata: z.record(z.union([z.string(), z.number().int(), z.boolean()]))
        .optional(),
    customFieldData: z.record(z.nullable(z.union([
        z.string(),
        z.number().int(),
        z.boolean(),
        z.date().transform(v => v.toISOString()),
    ]))).optional(),
    discountId: z.nullable(z.string()).optional(),
    allowDiscountCodes: z.boolean().default(true),
    amount: z.nullable(z.number().int()).optional(),
    customerId: z.nullable(z.string()).optional(),
    customerExternalId: z.nullable(z.string()).optional(),
    customerName: z.nullable(z.string()).optional(),
    customerEmail: z.nullable(z.string()).optional(),
    customerIpAddress: z.nullable(z.string()).optional(),
    customerBillingAddress: z.nullable(address_js_1.Address$outboundSchema).optional(),
    customerTaxId: z.nullable(z.string()).optional(),
    customerMetadata: z.record(z.union([z.string(), z.number().int(), z.boolean()])).optional(),
    subscriptionId: z.nullable(z.string()).optional(),
    successUrl: z.nullable(z.string()).optional(),
    embedOrigin: z.nullable(z.string()).optional(),
    productPriceId: z.string(),
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        customFieldData: "custom_field_data",
        discountId: "discount_id",
        allowDiscountCodes: "allow_discount_codes",
        customerId: "customer_id",
        customerExternalId: "customer_external_id",
        customerName: "customer_name",
        customerEmail: "customer_email",
        customerIpAddress: "customer_ip_address",
        customerBillingAddress: "customer_billing_address",
        customerTaxId: "customer_tax_id",
        customerMetadata: "customer_metadata",
        subscriptionId: "subscription_id",
        successUrl: "success_url",
        embedOrigin: "embed_origin",
        productPriceId: "product_price_id",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
var CheckoutPriceCreate$;
(function (CheckoutPriceCreate$) {
    /** @deprecated use `CheckoutPriceCreate$inboundSchema` instead. */
    CheckoutPriceCreate$.inboundSchema = exports.CheckoutPriceCreate$inboundSchema;
    /** @deprecated use `CheckoutPriceCreate$outboundSchema` instead. */
    CheckoutPriceCreate$.outboundSchema = exports.CheckoutPriceCreate$outboundSchema;
})(CheckoutPriceCreate$ || (exports.CheckoutPriceCreate$ = CheckoutPriceCreate$ = {}));
function checkoutPriceCreateToJSON(checkoutPriceCreate) {
    return JSON.stringify(exports.CheckoutPriceCreate$outboundSchema.parse(checkoutPriceCreate));
}
function checkoutPriceCreateFromJSON(jsonString) {
    return (0, schemas_js_1.safeParse)(jsonString, (x) => exports.CheckoutPriceCreate$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'CheckoutPriceCreate' from JSON`);
}
//# sourceMappingURL=checkoutpricecreate.js.map