/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { BenefitCustomSubscriberProperties$inboundSchema, BenefitCustomSubscriberProperties$outboundSchema, } from "./benefitcustomsubscriberproperties.js";
import { Organization$inboundSchema, Organization$outboundSchema, } from "./organization.js";
/** @internal */
export const BenefitCustomSubscriber$inboundSchema = z.object({
    created_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
    modified_at: z.nullable(z.string().datetime({ offset: true }).transform(v => new Date(v))),
    id: z.string(),
    type: z.literal("custom").optional(),
    description: z.string(),
    selectable: z.boolean(),
    deletable: z.boolean(),
    organization_id: z.string(),
    organization: Organization$inboundSchema,
    properties: BenefitCustomSubscriberProperties$inboundSchema,
}).transform((v) => {
    return remap$(v, {
        "created_at": "createdAt",
        "modified_at": "modifiedAt",
        "organization_id": "organizationId",
    });
});
/** @internal */
export const BenefitCustomSubscriber$outboundSchema = z.object({
    createdAt: z.date().transform(v => v.toISOString()),
    modifiedAt: z.nullable(z.date().transform(v => v.toISOString())),
    id: z.string(),
    type: z.literal("custom").default("custom"),
    description: z.string(),
    selectable: z.boolean(),
    deletable: z.boolean(),
    organizationId: z.string(),
    organization: Organization$outboundSchema,
    properties: BenefitCustomSubscriberProperties$outboundSchema,
}).transform((v) => {
    return remap$(v, {
        createdAt: "created_at",
        modifiedAt: "modified_at",
        organizationId: "organization_id",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var BenefitCustomSubscriber$;
(function (BenefitCustomSubscriber$) {
    /** @deprecated use `BenefitCustomSubscriber$inboundSchema` instead. */
    BenefitCustomSubscriber$.inboundSchema = BenefitCustomSubscriber$inboundSchema;
    /** @deprecated use `BenefitCustomSubscriber$outboundSchema` instead. */
    BenefitCustomSubscriber$.outboundSchema = BenefitCustomSubscriber$outboundSchema;
})(BenefitCustomSubscriber$ || (BenefitCustomSubscriber$ = {}));
export function benefitCustomSubscriberToJSON(benefitCustomSubscriber) {
    return JSON.stringify(BenefitCustomSubscriber$outboundSchema.parse(benefitCustomSubscriber));
}
export function benefitCustomSubscriberFromJSON(jsonString) {
    return safeParse(jsonString, (x) => BenefitCustomSubscriber$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'BenefitCustomSubscriber' from JSON`);
}
//# sourceMappingURL=benefitcustomsubscriber.js.map