/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const RepositorySortProperty = {
    CreatedAt: "created_at",
    MinusCreatedAt: "-created_at",
    Name: "name",
    MinusName: "-name",
    Stars: "stars",
    MinusStars: "-stars",
};
/** @internal */
export const RepositorySortProperty$inboundSchema = z.nativeEnum(RepositorySortProperty);
/** @internal */
export const RepositorySortProperty$outboundSchema = RepositorySortProperty$inboundSchema;
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var RepositorySortProperty$;
(function (RepositorySortProperty$) {
    /** @deprecated use `RepositorySortProperty$inboundSchema` instead. */
    RepositorySortProperty$.inboundSchema = RepositorySortProperty$inboundSchema;
    /** @deprecated use `RepositorySortProperty$outboundSchema` instead. */
    RepositorySortProperty$.outboundSchema = RepositorySortProperty$outboundSchema;
})(RepositorySortProperty$ || (RepositorySortProperty$ = {}));
//# sourceMappingURL=repositorysortproperty.js.map