/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { BenefitCustomProperties$inboundSchema, BenefitCustomProperties$outboundSchema, } from "./benefitcustomproperties.js";
/** @internal */
export const BenefitCustom$inboundSchema = z.object({
    created_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
    modified_at: z.nullable(z.string().datetime({ offset: true }).transform(v => new Date(v))),
    id: z.string(),
    type: z.literal("custom").optional(),
    description: z.string(),
    selectable: z.boolean(),
    deletable: z.boolean(),
    organization_id: z.string(),
    properties: BenefitCustomProperties$inboundSchema,
    is_tax_applicable: z.boolean(),
}).transform((v) => {
    return remap$(v, {
        "created_at": "createdAt",
        "modified_at": "modifiedAt",
        "organization_id": "organizationId",
        "is_tax_applicable": "isTaxApplicable",
    });
});
/** @internal */
export const BenefitCustom$outboundSchema = z.object({
    createdAt: z.date().transform(v => v.toISOString()),
    modifiedAt: z.nullable(z.date().transform(v => v.toISOString())),
    id: z.string(),
    type: z.literal("custom").default("custom"),
    description: z.string(),
    selectable: z.boolean(),
    deletable: z.boolean(),
    organizationId: z.string(),
    properties: BenefitCustomProperties$outboundSchema,
    isTaxApplicable: z.boolean(),
}).transform((v) => {
    return remap$(v, {
        createdAt: "created_at",
        modifiedAt: "modified_at",
        organizationId: "organization_id",
        isTaxApplicable: "is_tax_applicable",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var BenefitCustom$;
(function (BenefitCustom$) {
    /** @deprecated use `BenefitCustom$inboundSchema` instead. */
    BenefitCustom$.inboundSchema = BenefitCustom$inboundSchema;
    /** @deprecated use `BenefitCustom$outboundSchema` instead. */
    BenefitCustom$.outboundSchema = BenefitCustom$outboundSchema;
})(BenefitCustom$ || (BenefitCustom$ = {}));
export function benefitCustomToJSON(benefitCustom) {
    return JSON.stringify(BenefitCustom$outboundSchema.parse(benefitCustom));
}
export function benefitCustomFromJSON(jsonString) {
    return safeParse(jsonString, (x) => BenefitCustom$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'BenefitCustom' from JSON`);
}
//# sourceMappingURL=benefitcustom.js.map