"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.LegacyRecurringProductPrice$ = exports.LegacyRecurringProductPrice$outboundSchema = exports.LegacyRecurringProductPrice$inboundSchema = void 0;
exports.legacyRecurringProductPriceToJSON = legacyRecurringProductPriceToJSON;
exports.legacyRecurringProductPriceFromJSON = legacyRecurringProductPriceFromJSON;
const z = __importStar(require("zod"));
const schemas_js_1 = require("../../lib/schemas.js");
const legacyrecurringproductpricecustom_js_1 = require("./legacyrecurringproductpricecustom.js");
const legacyrecurringproductpricefixed_js_1 = require("./legacyrecurringproductpricefixed.js");
const legacyrecurringproductpricefree_js_1 = require("./legacyrecurringproductpricefree.js");
/** @internal */
exports.LegacyRecurringProductPrice$inboundSchema = z.union([
    legacyrecurringproductpricefree_js_1.LegacyRecurringProductPriceFree$inboundSchema.and(z.object({ amount_type: z.literal("free") }).transform((v) => ({
        amountType: v.amount_type,
    }))),
    legacyrecurringproductpricefixed_js_1.LegacyRecurringProductPriceFixed$inboundSchema.and(z.object({ amount_type: z.literal("fixed") }).transform((v) => ({
        amountType: v.amount_type,
    }))),
    legacyrecurringproductpricecustom_js_1.LegacyRecurringProductPriceCustom$inboundSchema.and(z.object({ amount_type: z.literal("custom") }).transform((v) => ({
        amountType: v.amount_type,
    }))),
]);
/** @internal */
exports.LegacyRecurringProductPrice$outboundSchema = z.union([
    legacyrecurringproductpricefree_js_1.LegacyRecurringProductPriceFree$outboundSchema.and(z.object({ amountType: z.literal("free") }).transform((v) => ({
        amount_type: v.amountType,
    }))),
    legacyrecurringproductpricefixed_js_1.LegacyRecurringProductPriceFixed$outboundSchema.and(z.object({ amountType: z.literal("fixed") }).transform((v) => ({
        amount_type: v.amountType,
    }))),
    legacyrecurringproductpricecustom_js_1.LegacyRecurringProductPriceCustom$outboundSchema.and(z.object({ amountType: z.literal("custom") }).transform((v) => ({
        amount_type: v.amountType,
    }))),
]);
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
var LegacyRecurringProductPrice$;
(function (LegacyRecurringProductPrice$) {
    /** @deprecated use `LegacyRecurringProductPrice$inboundSchema` instead. */
    LegacyRecurringProductPrice$.inboundSchema = exports.LegacyRecurringProductPrice$inboundSchema;
    /** @deprecated use `LegacyRecurringProductPrice$outboundSchema` instead. */
    LegacyRecurringProductPrice$.outboundSchema = exports.LegacyRecurringProductPrice$outboundSchema;
})(LegacyRecurringProductPrice$ || (exports.LegacyRecurringProductPrice$ = LegacyRecurringProductPrice$ = {}));
function legacyRecurringProductPriceToJSON(legacyRecurringProductPrice) {
    return JSON.stringify(exports.LegacyRecurringProductPrice$outboundSchema.parse(legacyRecurringProductPrice));
}
function legacyRecurringProductPriceFromJSON(jsonString) {
    return (0, schemas_js_1.safeParse)(jsonString, (x) => exports.LegacyRecurringProductPrice$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'LegacyRecurringProductPrice' from JSON`);
}
//# sourceMappingURL=legacyrecurringproductprice.js.map