/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { CheckoutLinkCreateProduct$inboundSchema, CheckoutLinkCreateProduct$outboundSchema, } from "../components/checkoutlinkcreateproduct.js";
import { CheckoutLinkCreateProductPrice$inboundSchema, CheckoutLinkCreateProductPrice$outboundSchema, } from "../components/checkoutlinkcreateproductprice.js";
import { CheckoutLinkCreateProducts$inboundSchema, CheckoutLinkCreateProducts$outboundSchema, } from "../components/checkoutlinkcreateproducts.js";
/** @internal */
export const CheckoutLinksCreateCheckoutLinkCreate$inboundSchema = z.union([
    CheckoutLinkCreateProductPrice$inboundSchema,
    CheckoutLinkCreateProduct$inboundSchema,
    CheckoutLinkCreateProducts$inboundSchema,
]);
/** @internal */
export const CheckoutLinksCreateCheckoutLinkCreate$outboundSchema = z.union([
    CheckoutLinkCreateProductPrice$outboundSchema,
    CheckoutLinkCreateProduct$outboundSchema,
    CheckoutLinkCreateProducts$outboundSchema,
]);
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var CheckoutLinksCreateCheckoutLinkCreate$;
(function (CheckoutLinksCreateCheckoutLinkCreate$) {
    /** @deprecated use `CheckoutLinksCreateCheckoutLinkCreate$inboundSchema` instead. */
    CheckoutLinksCreateCheckoutLinkCreate$.inboundSchema = CheckoutLinksCreateCheckoutLinkCreate$inboundSchema;
    /** @deprecated use `CheckoutLinksCreateCheckoutLinkCreate$outboundSchema` instead. */
    CheckoutLinksCreateCheckoutLinkCreate$.outboundSchema = CheckoutLinksCreateCheckoutLinkCreate$outboundSchema;
})(CheckoutLinksCreateCheckoutLinkCreate$ || (CheckoutLinksCreateCheckoutLinkCreate$ = {}));
export function checkoutLinksCreateCheckoutLinkCreateToJSON(checkoutLinksCreateCheckoutLinkCreate) {
    return JSON.stringify(CheckoutLinksCreateCheckoutLinkCreate$outboundSchema.parse(checkoutLinksCreateCheckoutLinkCreate));
}
export function checkoutLinksCreateCheckoutLinkCreateFromJSON(jsonString) {
    return safeParse(jsonString, (x) => CheckoutLinksCreateCheckoutLinkCreate$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'CheckoutLinksCreateCheckoutLinkCreate' from JSON`);
}
//# sourceMappingURL=checkoutlinkscreate.js.map