/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ListResourceUnionPaymentMethodCardPaymentMethodGeneric$inboundSchema, ListResourceUnionPaymentMethodCardPaymentMethodGeneric$outboundSchema, } from "../components/listresourceunionpaymentmethodcardpaymentmethodgeneric.js";
/** @internal */
export const CustomerPortalCustomersGetPaymentMethodsSecurity$inboundSchema = z.object({
    customer_session: z.string(),
}).transform((v) => {
    return remap$(v, {
        "customer_session": "customerSession",
    });
});
/** @internal */
export const CustomerPortalCustomersGetPaymentMethodsSecurity$outboundSchema = z.object({
    customerSession: z.string(),
}).transform((v) => {
    return remap$(v, {
        customerSession: "customer_session",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var CustomerPortalCustomersGetPaymentMethodsSecurity$;
(function (CustomerPortalCustomersGetPaymentMethodsSecurity$) {
    /** @deprecated use `CustomerPortalCustomersGetPaymentMethodsSecurity$inboundSchema` instead. */
    CustomerPortalCustomersGetPaymentMethodsSecurity$.inboundSchema = CustomerPortalCustomersGetPaymentMethodsSecurity$inboundSchema;
    /** @deprecated use `CustomerPortalCustomersGetPaymentMethodsSecurity$outboundSchema` instead. */
    CustomerPortalCustomersGetPaymentMethodsSecurity$.outboundSchema = CustomerPortalCustomersGetPaymentMethodsSecurity$outboundSchema;
})(CustomerPortalCustomersGetPaymentMethodsSecurity$ || (CustomerPortalCustomersGetPaymentMethodsSecurity$ = {}));
export function customerPortalCustomersGetPaymentMethodsSecurityToJSON(customerPortalCustomersGetPaymentMethodsSecurity) {
    return JSON.stringify(CustomerPortalCustomersGetPaymentMethodsSecurity$outboundSchema.parse(customerPortalCustomersGetPaymentMethodsSecurity));
}
export function customerPortalCustomersGetPaymentMethodsSecurityFromJSON(jsonString) {
    return safeParse(jsonString, (x) => CustomerPortalCustomersGetPaymentMethodsSecurity$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'CustomerPortalCustomersGetPaymentMethodsSecurity' from JSON`);
}
/** @internal */
export const CustomerPortalCustomersGetPaymentMethodsRequest$inboundSchema = z.object({
    page: z.number().int().default(1),
    limit: z.number().int().default(10),
});
/** @internal */
export const CustomerPortalCustomersGetPaymentMethodsRequest$outboundSchema = z.object({
    page: z.number().int().default(1),
    limit: z.number().int().default(10),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var CustomerPortalCustomersGetPaymentMethodsRequest$;
(function (CustomerPortalCustomersGetPaymentMethodsRequest$) {
    /** @deprecated use `CustomerPortalCustomersGetPaymentMethodsRequest$inboundSchema` instead. */
    CustomerPortalCustomersGetPaymentMethodsRequest$.inboundSchema = CustomerPortalCustomersGetPaymentMethodsRequest$inboundSchema;
    /** @deprecated use `CustomerPortalCustomersGetPaymentMethodsRequest$outboundSchema` instead. */
    CustomerPortalCustomersGetPaymentMethodsRequest$.outboundSchema = CustomerPortalCustomersGetPaymentMethodsRequest$outboundSchema;
})(CustomerPortalCustomersGetPaymentMethodsRequest$ || (CustomerPortalCustomersGetPaymentMethodsRequest$ = {}));
export function customerPortalCustomersGetPaymentMethodsRequestToJSON(customerPortalCustomersGetPaymentMethodsRequest) {
    return JSON.stringify(CustomerPortalCustomersGetPaymentMethodsRequest$outboundSchema.parse(customerPortalCustomersGetPaymentMethodsRequest));
}
export function customerPortalCustomersGetPaymentMethodsRequestFromJSON(jsonString) {
    return safeParse(jsonString, (x) => CustomerPortalCustomersGetPaymentMethodsRequest$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'CustomerPortalCustomersGetPaymentMethodsRequest' from JSON`);
}
/** @internal */
export const CustomerPortalCustomersGetPaymentMethodsResponse$inboundSchema = z.object({
    Result: ListResourceUnionPaymentMethodCardPaymentMethodGeneric$inboundSchema,
}).transform((v) => {
    return remap$(v, {
        "Result": "result",
    });
});
/** @internal */
export const CustomerPortalCustomersGetPaymentMethodsResponse$outboundSchema = z.object({
    result: ListResourceUnionPaymentMethodCardPaymentMethodGeneric$outboundSchema,
}).transform((v) => {
    return remap$(v, {
        result: "Result",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var CustomerPortalCustomersGetPaymentMethodsResponse$;
(function (CustomerPortalCustomersGetPaymentMethodsResponse$) {
    /** @deprecated use `CustomerPortalCustomersGetPaymentMethodsResponse$inboundSchema` instead. */
    CustomerPortalCustomersGetPaymentMethodsResponse$.inboundSchema = CustomerPortalCustomersGetPaymentMethodsResponse$inboundSchema;
    /** @deprecated use `CustomerPortalCustomersGetPaymentMethodsResponse$outboundSchema` instead. */
    CustomerPortalCustomersGetPaymentMethodsResponse$.outboundSchema = CustomerPortalCustomersGetPaymentMethodsResponse$outboundSchema;
})(CustomerPortalCustomersGetPaymentMethodsResponse$ || (CustomerPortalCustomersGetPaymentMethodsResponse$ = {}));
export function customerPortalCustomersGetPaymentMethodsResponseToJSON(customerPortalCustomersGetPaymentMethodsResponse) {
    return JSON.stringify(CustomerPortalCustomersGetPaymentMethodsResponse$outboundSchema.parse(customerPortalCustomersGetPaymentMethodsResponse));
}
export function customerPortalCustomersGetPaymentMethodsResponseFromJSON(jsonString) {
    return safeParse(jsonString, (x) => CustomerPortalCustomersGetPaymentMethodsResponse$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'CustomerPortalCustomersGetPaymentMethodsResponse' from JSON`);
}
//# sourceMappingURL=customerportalcustomersgetpaymentmethods.js.map